travis:
  secure:
    BINSTAR_TOKEN: KCUHjmvQ11W0y30HLqtPLb2UyRonB0HxeyhlzsRDDapIy9NhT51RIXOKTj+gk7g+sMC6FU0LvsHCYQk7u8q5MZJTZYqzOjmPoRbFqb0ZS6RjTtiWR+1xRBvxrfYkruprvrS0PzsH09sgd24X8SkFY6zeIhMR08z7YCb7t+zB4BvSm13XQmNmxOy7jtVgoCd6ndgNgpxQ5HggSWQP1LMusxyvQQUPqSW+mo3ihvNBucfUbxFjAJOo+zgdbX9P1Ju/fNNWX1kP3FU7nzAwGzwekGwP3lHkqzUKVG6aHKUud5Jlyye3r/gDyM92gStsPrzna+N36yxDyGWaQIO133Om95FvEzxIyzpoaVQDXouKMLgfX99MnGZTsz8IisZAuOhumNM5O/HVQUjdEoYX6MP9bzWb4UWTEgnNmTZAs7Qn7xK1LINDwtC18mfGyLXUaJrjrEzJZOLxbZWcUSga8vrE3ZUX0GfDriai6EurpbiWOU36qWAoqtruqQX2ya9b5hPwqUyvnTvsUyaxKC8HVo7veByyhB+V8VgrYzKnl0JMmwuSKIZ4MsnL28x1J8aLuhCPJuMThjbvTmB8J7YHsOkVomW3Jo99/HxvGNxk14CNUMceo+eIhgZ0X8aGad7PJBH5emcA+7P7P4ramXWXtqeus3SylzXocsI/NBtIa5vPZ/k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
